# Generated by Django 4.1.1 on 2022-09-05 14:20

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=django_jsonform.models.fields.JSONField(),
        ),
    ]
